# Настройки Telegram
Telegram:
   Token: "" # Токен доступа, создаётся в @BotFather

# Сервисы проверки сообщений на предмет спам-а
Spam:
   Akismet:
      ApiKey: "" # Ключ доступа а API (Можно получить в настройках одноименного WordPress плагина)
      SiteURL: "" # Подставляется при запросе к сервису (Обычно это блок на WordPress). Например: https://zixn.ru
   Common:
      ResponseWaitingTime: 10 # Время ожидания ответа до блокировки в секундах для нового пользователя
Log:
   FilePath: "app.log" # путь к файлу
   Level: "info" # уроверь логирования