name: Build and Commit Binaries

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'build/**'
      - '**.md'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Create build directory
        run: mkdir -p build

      - name: Build Windows
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 0
        run: go build -o build/app-windows-amd64.exe cmd/tegobot/main.go

      - name: Build Linux
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: go build -o build/app-linux-amd64 cmd/tegobot/main.go

      - name: Build Android
        env:
          GOOS: android
          GOARCH: arm64
          CGO_ENABLED: 0
        run: go build -o build/app-android-arm64 cmd/tegobot/main.go

      - name: Commit and Push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add build/
          git diff --quiet && git diff --staged --quiet || git commit -m "[skip ci] Add built binaries"
          git push